micronaut:
  application:
    name: mn-ktor-reactiveMongo-no2

logger:
  levels:
    io.micronaut.http: DEBUG


mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/flows_channels

ejf:
  secretkeyid: secret_is_here
  key_id: jf2
  
  jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false